---
title: Tricky English words and phrases-2
author: Qing-Zeng Zhu
date: '2021-07-04'
slug: english-vovabulary-2
categories:
  - education
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-07-04T13:32:40+02:00'
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


Some politicians and representatives of the military-industrial complex using China as the latest **pretext** for larger and larger defense budgets. (托词: a pretext is a reason that you pretend has caused you to do something)

The period that was broadly described as **engagement with China** has come to an end and that going forward, the dominant **paradigm** is going to be competition. (范例: A **paradigm** is a model for something that explains it or shows how it can be produced)

Mental health needs a powerful **spot light** (聚光灯), staring with us coming out to speak about it and advocating to end **mental health stigma**. (污名)

Your response to my plan **deflated** me. (make sb feel less confident; to make sb/sth feel or seem less important 使泄气).

Stop **making light of life**. (轻视)

Apparently, he didn’t want to **be made light of**. (被小瞧)

A **fire drill** is a method of practicing how a building would be evacuated in the event of a fire or other emergency. (消防演习)

How to use a **fire extinguisher**? (消防栓)

**Plainclothes police** (便衣警察) detained Lei-yang and beat him to death.

“Foot massage parlor” is a common Chinese **euphemism for** a brothel. (委婉说法)

Do you know how to separate the **egg white** from **egg yolk**?
 
How to **whip eggs**?

The **pension system** is a black hole and requires trillions of dollars. (退休金系统)

When you arrive at Tibet, don’t activate immediately, otherwise, you will have **altitude sickness**. (高原反应)

You have to have a lot of **stamina** to be a top-class pianist. (毅力)

Unable to **resist the impulse**, he glanced at the sea again. (抑制冲动)

The necklace was an **impulse buy**. (冲动消费)

Don’t act **on impulse**. (冲动)

World War I **left an indelible imprint on** the twentieth-century world. (难以磨灭的印记)

The football match was **imprinted** on my memory. (铭刻)

The old house near the school became a **repository** for police files. (存放处)

In many non-Western societies, however, monogamy has never dominated.
Polygamy. (一夫一妻制，一夫多妻制)

He **was obliged to** resign when one of his own aides was implicated in a financial scandal. (被迫)

Your **perception** of something is the way that you think about it or the impression you have of it. (认知)
He is interested in how our **perceptions of death** affect the way we live. (对死亡的认知)

Antonio Rudiger has insisted Chelsea **thrive on** (If you say that someone thrives on a particular situation, you mean that they enjoy it or that they can deal with it very well, especially when other people find it unpleasant or difficult, 从容应对) being Champions League **underdogs** (比赛中不被看好一方)  - and warned they are ready to beat Manchester City for a third time.

Meng Wanzhou is being held by **extraterritorial application** of America law. (域外法权)

Get any universities or institutes to do an objective evaluation: which country, US or China, abides by **the rules-based international order**. (基于规则的秩序)

Are you telling me it is **not in American’s interest to** cooperate with China? (符合…利益)

The book “Has China Won” **outrage** American readers. (震怒). One tweet last evening really provoked outrage from women.

Without continued learning, I will lose my intellectual **vitality** (活力). 

US has failed to develop any **coherent** strategy to deal with a resurgent China, Kishore Mahbubani argues. (连贯的，一致的)

My Ph.D. goal emphasizes problem-solving, critical thinking, writing, and **hands-on experience**. (动手能力)

The young use VPNs (virtual private network) to cross the firewall so that they can access Facebook and Youtube. (防火墙)

His bad breath was really a big **turn-off** to the party. (扫兴)

Staying in academia requires **perseverance and dedication**.

Being humorous makes life easier and simpler. 

The film star is the **brand ambassador** of Armani. (品牌大使)

Do remember wear the life vest when you are on board.

Honey was considered the food of the Gods in ancient Egypt. Beehive is a masterpiece, maximum volume with minimum use of materials

It’s like the emptiness I’ve always had has gone.

People want to use scientific technologies to **transcend** our biological limitations. (something that transcends normal limits or boundaries goes beyond them, because it is more significant than them 超越) 

You abandon yourself emotionally, physically, spiritually, financially, relationally, and or organizationally, you automatically make your partner responsible for you.

You can buy food at this market **24/7**.

Let’s **get the ball rolling**.

I know my hometown **like the back of my hand**.

**There is no way I can** finish the experiments on time.

What are the **chances** of getting a ticket? (概率)

It totally **slipped off my mind**. (完全忘记)

I bought a **chalk bag** and chalk ball yesterday. (防滑粉袋)

Most people working in big companies receive a substantial part of their income in the form of bonus and overtime

They began doing business **as far back as** the Second World War. (追随到)

The bank agreed to grant loans to me. (贷款)

How to remove the tea stains and coffee stains? (茶垢，咖啡垢)

They debated the pros and cons of setting up their firm. (利弊)

Our **perceptions** of the candidates can be influenced by their voice. The candidates with lower voices **are more likely to win** than a high-pitched opponent. It’s probably because our preconceptions are that people with lower voices are older, stronger, and more competent. A deep voice is associated with high testosterone, physical strength, and aggression. High-pitched voices are thought to convey negative emotions such as stress and fear.

China was falling behind in science and technology. Absorbing potential companies was the quickest way to get rid of the technological gap between China and developed countries. Based on this, subsequent research and development will ensure the competiveness of Chinese products. The state-owned enterprises are now trying to purchase the patents and techniques, merging famous companies like IBM. Now CHEMCHINA is trying to purchase Syngenta company with an offer of 43 billion dollars. 

The travel agency arranged everything, the hotel, the schedule, the route. But the **drawback** is that we don’t have enough time to visit each place.

You must get rid of the **sense of inferiority**. (自卑情结) 
French people have an ingrained **superiority complex** in them. 
The windows are completely shattered during the explosion (粉碎).
You can choose the sensor mode and then the Turbo Vap will stop automatically when the liquid level is lower than the sense line. 

The contract or agreement has no **legal effect**. (法律效力)

View of life: how should we live our life.
View of value: what is more valuable? What is most precious in our life. What means the most to you.
Worldview: what is the world like?

Scientific discoveries have discredited religious belief (败坏名声，使失去权威性).

Most people in China are **atheists**. **Atheism** is the prominent worldview of Chinese. (无神论)

The child’s eyes were wide open with wonder at the fireworks.

The storm wrecked many houses in the town.

The house was a wreck after the party.

Searchers found the **wreckage** of the plane on high mountains. (残骸)

She **waved at** me far away. (挥手)

Angela Merkel is a wise leader and makes a series of **economy stimulus policy** for recovery from the economic recession. (经济刺激措施)

Kids are **plastic**. (可塑性强的)

The holiday **lasted for** about four days.

The company withdrew the disputed products and maintained the reputation of their brands.

Twelve people were wounded during the demonstration.

There is a wide choice of products in the supermarket. 

She conceded that I was right.

Culture can be ordered into layers, like an onion, where one peel has to be taken off in order to see the following layer. Cultures can be divided into the High-context culture and Low-context culture. For example, China, a typical High-context culture country, people living in China tend to communicate in a more ambiguous implicit way. While the USA is low-context culture and they separate the issues from the person.

The carabiner must be used in rock climbing to be on the safe side.
Vinegar can act as acid descaler to remove the limescales in the kettle.
I have a bad running nose.
I feel like I am blowing my nose every 10 seconds.
I have a stuffy nose, I can’t smell anything 
I have a sore throat.
I have a really bad cough

You can’t leave me hanging here.
Hang on, I have another call.

Hang up on someone... 
She broke up with her boyfriend a year ago, but she still hangs up on him.

Are you hanging up on someone? 

Keep it up. Hang in there 

Studying pays off. 

My boss fired me today out of nowhere. I couldn’t believe my ears when he told me to pack my stuff and go.

Play it by ear. I am not sure how long I will stay at the party, I guess I’ll just play it by ear!

I will follow my nose.

Cross your finger for me! 

Zip your lip.

My lips are sealed. 

This bed couch is really springy.

Don’t be a couch potato. It’s not a healthy lifestyle.

He is still under police surveillance. 

More than 65% messages are communicated nonverbally.

When we’re isolated in a storm, we will recognize how puny humans are when compared to such powerful forces as ice storms and snow drifts.

The feudal hierarchy has a big impact on the society of China nowadays.

The Black Death in the late 14th century killed more than one-third of the European population.

The Economic Depression of 1929 in the US resulted in a serious consequence. Millions of people lost their jobs.

Cultural Revolution of China resulted in millions of cultural relics being destroyed.

2nd March is my lunar year birthday, and my calendar year birthday is in April.

I milked the cow in the farm 

As devastating as Ebola is, it’s also inspired one of the most extraordinary achievements in medical history.

I participated in my first marathon in 2014, and it was an incredible experience.

Think of work as a series of sprints, not a marathon.

My favorite TV show is the big bang theory because it’s hilarious. 

My favorite character on the Big Bang Theory is obviously Sheldon, his nerdiness and total lack of social skills make his character so funny.

My favorite episode

Easter bunny. 
Easter basket.
They usually stuff Easter basket with tons of Easter candy.
Easter egg hunt 

Tom gets **tongue-tied** whenever he sees her because she is so beautiful.

You have ants in your pants about somethings today.


Walking home alone at night gives me the heebie-jeebies (the feeling of being nervous)

Don’t get worked up. 

## The Oscars.
Best Picture

The movie Hugo is nominated for the Best Picture at the Oscars.

The Artist won the Oscar for Best Picture.

The movie “Spotlight” won the Oscars for Best Picture

The movie was set in pre-war London (以…为背景)

The box office is not that satisfying. (票房)

The film, Batman vs superman which is directed by Christopher Nolan is to be released in 2016 and I am looking forward to it. (放映)

The film will be premiered on January 18, 2016. (首映)

I am not a fan of scary movies; scary movies give me nightmares.

I am not a fan of soap opera, it’s so cheesy (If you describe something as cheesy, you mean that it is cheap, unpleasant, or insincere, 俗气的，庸俗的). 

What’s getting you down?

He keeps **talking behind my back**. 

It takes some getting used to.

What time does your train depart?

The train to New York will depart from platform 3 in half an hour.

The train will arrive in New York at 8

Metro stop

This is the third time in a row. 

You can find the information in the cache files.

I don’t like people with a serious expression.

It’s like an elastic band

He is always forgiving. 

Mix the meat with the onion, carrot, and some seasoning.

Don’t mock other people’s flaws.

I have to take my kid to school in the morning and pick him up in the afternoon.

You must be popular with friends.
Why? Because you are outgoing, honest and beautiful.

They don't have any confidence that houses will appreciate/depreciate in value 

No one can solve the riddle of the birth of human being and the universe.

Dichloromethane is suspected to be a **carcinogenic substance**. (致癌物质)

Every so often a truly groundbreaking idea comes along. 

Why brains and talent don’t bring success? How can they stand in the way of it? (挡住去路，阻碍) Why praising brains and talent doesn’t foster self-esteem and accomplishment, but jeopardizes them? How teaching a simple idea about the brain raises grades and productivity? Mindset is a simple idea discovered by world-renowned Stanford University psychologist Carol Dweck in decades of research on achievement and success—a simple idea that makes all the difference. In a fixed mindset, people believe their basic qualities, like their intelligence or talent, are simply fixed traits. They spend their time documenting their intelligence or talent instead of developing them. They also believe that talent alone creates success—without effort. They’re wrong. In a growth mindset, people believe that their most basic abilities can be developed through dedication and hard work—brains and talent are just the starting point. This view creates a love of learning and a resilience that is essential for great accomplishment. Virtually all great people have had these qualities. Teaching a growth mindset creates motivation and productivity in the worlds of business, education, and sports. It enhances relationships. When you read Mindset, you’ll see how.

I tend to have a positive mindset now.

Of a nation, of the world. (民族的就是世界的)

## Orchestra
Orchestra chief

Podium 指挥台

Swing the **baton**. 指挥棒

The conductor wears the **tailed suit**. 燕尾服

The conductor standing on the podium is swinging the baton to rehearsal the new musical compositions.

I used to play in a Chinese Orchestra and I missed the time when players get together and play. 

I found the record when I organize the files on my computer\ in my hard disk\ in my removable HDD.

Will they **reimburse you**? I think they will reimburse me. 报销
Which department do you want to register with? (你要挂哪科的号)
I want to see a physician, internist 内科医生, surgeon 外科医生, obstetrician 产科医生, gynecologist 妇科医生, pediatrician 儿科医生, neurologist 神经科医生, dermatologist 皮肤科医生, oculist 眼科医生, specialist 专科医生, allergist 过敏症专科医生, urologist 泌尿科医生, orthopedist 整形外科医生, dentist 牙科医生, endocrinologist 内分泌科医生

These are not necessarily hateful, **malicious people**. 怀有恶意的人

I have to buy a **scalping ticket** because the queue is too long. (黄牛票)

The rime in Bremen park is beautiful. 雾凇

**Disposable gloves** are used in the isotopic lab.
You can use the **wet wipe** to clean the fat and oil on your hand.

He is a bad apple

She is the apple of everyone’s eye

It’s like comparing apple and oranges.

Crimp =small hold (climbing)
Top-rope climbing
Bouldering
Do you like bouldering?
Bouldering means rock climbing on large boulders or small outcrops either as practice or as a sport in its own right.

Sour grapes.
Graffiti=doodling

Slackline
Rookie 菜鸟
Reading a scientific paper should not be done in a linear way (from beginning to end); instead, it should be done strategically and with a critical mindset, questioning your understanding and the findings. 

My friend set me up on a blind date but she was not my type

You are dead meat. 

Your forced smile hurt me. 

Don’t mock other people’s flaws. 

I really dig your shoes

Bad breath is really a big turn-off. 

Your body odor is weird.

## Basketball:
point guard

shooting guard center

power forward

small forward

dribbling 

## Football:
Round of 16(first leg, second leg)

Quarterfinals

Semifinals 

Finals 

Barcelona wins against Arsenal in the first **Knock-out round**. (淘汰赛)

**Away goal** is more valuable than **home goal**. 

Chelsea won on **away goals** against PSG. 

Spain La Liga 

Germany Bundesliga 

France Ligue 1

England Premier League 

Italy Seria A

Europa league Champions league 

European championship 

Now Chelsea is far away from the **relegation zone**.  (降级区)

Ramires chooses to leave due to the lack of first-team opportunities.

left back <br> center back  <br> center back <br> right back

defending midfielder  <br> central midfielder 

left winger <br> right winger

striker(forward) 



nothing cools me down better than ice cream

nothing puts me to sleep better than classical music

nothing cheers me up better than a girlfriend

It will be difficult to fill his shoes because he did a great job

If the shoe fits, wear it.

What would you do if you were in my shoes.

He is being **chivalrous**. (有骑士风度的)

You can rock a dress.

Does this shirt **go with** my shoes? (…与…搭配吗)

she is always sticking her nose into other people's business.

I can never remember people's names and they go in one ear and out the other.

<p style="color:Tomato;">*When I was young and free and my imagination had no limits, I dreamed of changing the world. *</p>

<p style="color:Tomato;">*As I grew older and wiser, I discovered the world would not change, so I shortened my sights somewhat and decided to change only my country. But it, too, seemed immovable. * </p>


<p style="color:Tomato;">*As I grew into my twilight years, in one last desperate attempt, I settled for changing only my family, those closest to me, but alas, they would have none of it. *</p>


<p style="color:Tomato;">*And now, as I lie on my deathbed, I suddenly realize: If I had only changed myself first, then by example I would have changed my family. From their inspiration and encouragement, I would then have been able to better my country, and who knows, I may have even changed the world. *</p>



The world is your oyster (世界是属于你的， 你可以随心所欲施展自己)
 
It really takes my breath away

snack stand 

feast my eyes on this 

it's always packed= it's always crowded.

Checkmate

Sometimes you cannot have your cake and eat it too. (不可能处处随人愿) 

I don't feel good and I am going to **call in sick** and **take the day off** (请病假). 

Over 200 million people are expected to take the train over this year's spring festival. that's the biggest humanity movement in the world.

In China, fireworks are used to **drive away** evil (驱赶). Right after midnight fireworks are set off. It is believed that the person who launched the first fireworks of the year will have good luck. People use the reflections of the fireworks in the lake to **enhance the display**. Some people even spell their names in the sky with fireworks.

I have an easy schedule

**When it rains, it pours** (祸不单行) 

oh, I missed my chance, coulda, woulda, shoulda, 早知如此，何必当初

FYI：for your information
Just an FYI, I'll be out of town next week.

The food is **mouldy**. (发霉)

BRB: be right back.

LOL: laugh out loud

TMI: too much information

I always give in too easily and I gotta hang tough

He wears her heart on her sleeve 

Break the rules and stand apart, ignore your head and follow your heart. 

You are a hopeless romantic

puppy love 早恋

The price of cucumber is **sky-high**

Time is slipping away through my fingers.

In spite of all your hard work, you are not approaching your goals. Soon this may even become your daily mantra: Why am I not approaching my target when I’m running so fast?

It may feel like you’re making one step forward and two steps back.

The lack of proper prioritization is one of the main **pitfalls** on the road to getting a Ph.D. (隐患)

Loofa 洗澡海绵

she is the life of party, party pooper, party animal, wallflower, social butterfly. 

How long will it take to get over this relationship ((从不快或疾病中) 恢复过来) 

It took her a very long time to get over the shock of his death.

He is bound to succeed because he trained so damn hard.

It **smells** like a bad choice.

We will send you a text message stating the **roaming costs** (漫游) after you connect to a network abroad.

Data roaming **is capped at** 50€/month to help you keep roaming charges under control. (封顶)

Remember to **top up** your phone (充值)

