---
title: Tricky English words and phrases-1
author: Qing-Zeng Zhu
date: '2021-05-19'
slug: english-vocabulary-1
categories:
  - education
tags: []
subtitle: ''
summary: 'As a English learner, I am sharing some words and phrases from news or articles that I think are tricky. Hopefully it will be helpful to enrich our expressions whenever we want to discuss a certain topic or write a blog.'
authors: []
lastmod: '2021-05-19T19:58:31+02:00'
featured: no
draft: no
image:
  caption: '[photo from Sara DIB](https://www.linkedin.com/pulse/lets-learn-english-sara-dib)'
  focal_point: ''
  preview_only: no
projects: []
---
Sometimes I experience **sleep paralysis**. (鬼压床)

Trump called for much stricter **curbs** on immigration. (限制)

Supporters say that as a major player in international politics, China’s viewpoint deserves to be heard. Opponents, however, worry that the world’s media are becoming too **credulous** of China. (轻信的)

I do not know whether he is **adequate** for this job. (胜任)

H&M became **cannon fodder** under the so-called anti-Xinjiang cotton. (炮灰)

Chewing **khat** is part of some social traditions in parts of the Middle East, such as Saudi Arabia and Yemen, and in Eastern Africa, such as Somalia. (卡特叶)

If someone **decries** an idea or action, they criticize it strongly. (强烈批评) England’s $32 billion tests and trace system has not made a clear impact on the progress of COVID-19, the British Parliament’s Public Accounts Committee said, decrying the 'unimaginable' costs of the program

This building can **stand up to** a 7-magnitude earthquake. (经受住) We should resolutely **stand up to** polarization and make policies based on reasons and facts. 
<p style="color:Tomato;">It takes a great deal of bravery to **stand up to** your enemies, but a great deal more to **stand up to** your friends.</p>

I agreed to be here on debate but not **on trial**. (受审) You should give me time to express my opinion. Where is your so-called freedom, only applies to you and not everyone else in the other countries? 

A **backlash** against a tendency or recent development in society or politics is a sudden, strong reaction against it. (对政治或社会变化的) 强烈反对 This meeting caused a backlash against racism.

If a person, company, or country **defaults on** something that they have legally agreed to do, such as paying some money or doing a piece of work before a particular time, they fail to do it. (违约) Because of the 2008 crisis, many people defaulted on housing loans. The company may be charged with default on its contract with the government. 

Nick's bank sent him a letter saying he was $500 **overdrawn**. (透支) You risk incurring bank charges if you exceed your **overdraft** limit. 

Sina **went public** in 2000 on Nasdaq and agreed to **go private** in 2020 (上市和退市)

He would not **appeal** the court’s decision. (申诉)

Someone who is **assertive** states their needs and opinions clearly, so that people take notice. (坚定自信的) Women have become more assertive in the past decade.

Someone who is **self-assertive** acts in a confident way, speaking firmly about their opinions and demanding the rights that they believe they should have. (有主见的) If you want good relationships, you must have the confidence to be self-assertive when required. 

"We fully **retract** this paper from the published record," Lancet editors said in a statement on Tuesday. (撤销)

**Anti-intellectualism** is hostility to and mistrust of intellect, intellectuals, and intellectualism, commonly expressed as deprecation of education and philosophy and the dismissal of art, literature, and science as impractical, politically motivated, and even contemptible human rights. (反智)

A **totalitarian political system** is one in which there is only one political party which controls everything and does not allow any opposition parties. (极权主义)

**Containment** is the action or policy of keeping another country's power of control within acceptable limits. Us cannot rid itself of containment mindset. (遏制)

My laptop **crashed** again. (崩溃)

**Financial oligarch**. (金融寡头)

**Heresy** is a belief or action which seriously disagrees with the principles of a particular religion. (异教)

This is **trampling on human rights**. (践踏)

**Living paycheck to paycheck** is a way of life for the majority of US workers.(入不敷出)

I am completely **on board** about working with Chinese in a new economic order in the world. (支持)

They are well-mannered and ill-mannered. (举止端庄，举止粗鲁) 

An absolute **disgrace** to journalism. (耻辱)

Those questions are full of prejudice and had no knowledge of facts. These journalist **got slapped in the face left and right**. (啪啪打脸)

Joaquin Phoenix’s Joker won a **box office** of over 1 billion. (票房) Health Ledger’s role as the Joker in The Dark Knight earned him widespread acclaim and popularity from both fans and critics alike.

In the past 23 years, three US presidents **launched the “war on terror”**, invading 9 Muslim countries and killing millions of Muslims. Therefore, the US has not solved the problem of extremist Muslims at all. It is the United States that say to kill them all.(发动战争)


**Suffrage** is the right of people to vote for a government or national leader. Woman's suffrage movement. (普选)

The **ramifications** of a decision, plan, or event are all its consequences and effects, especially ones that are not obvious at first. (后果) I do not believe there was any consideration for the consequences and ramifications of the tweet.

If you describe someone as **moody**, you mean that their feelings and behavior change frequently, and in particular that they often become depressed or angry without any warning. (喜怒无常的) David's mother was unstable and moody. A moody person can go to emotional extremes in a short period of time.

A salesperson's **sales pitch** is what they say in order to persuade someone to buy something from them. (卖点) His sales pitch was smooth and convincing. 


She stood me up. (放鸽子)

If you want to keep your job, **toe the line** (do what is expected and not overdo something)

If you have a **grudge against someone**, you have unfriendly feelings toward them because of something they did in the past. (积怨) He appears to have a grudge against certain players. 

653 US athletes applied for **therapeutic use exemption** and 402 of them have been approved. However, less than 20 have been approved in 54 Russia athletes. 

The vessel used for measuring spirit is called **jigger**.

**Polio** is a serious infectious disease that often makes people unable to use their legs (小儿麻痹症) Gladys was crippled by polio at the age of 3. 

Today, I got a stomach flu. (肠胃炎)

If someone has a **fetish**, they have an unusually strong liking or need for a particular object or activity, as a way of getting sexual pleasure. rubber and leather fetishes, fetish wear for sexual arousal. (恋物癖)

**Burnout** is now an official medical diagnoses, according to World Health Organization.

**Bogeyman** is a mythical creature used by adults to frighten children into good behavior

How to Identify and Avoid Common **Phone Scams**. (诈骗电话)

I thought I was unfairly treated. I did the work but someone else **took the credit**. (抢功劳)

They behaved with more **restraint** than I'd expected. (克制的) 

Huawei has repeatedly denied the accusations, and called on the Trump administration to provide evidence to **back up** its claims. (支持)


 
**Tipping point**: the point at which the number of small changes over a period of time reaches a level where a further small change has a sudden and very great effect on a system or leads to an idea suddenly spreading quickly among a large number of people. (临界点)

The world is now watching to see where this research revolution will go next - and whether China can complete its **transformation into a global science powerhouse**.

Some believe that China is moving too quickly, without assessing the risks - or the **ethics**.

**Animal-to-human-transplantation** is just one area where China is straying on to the controversial ground. Work on stem cells, cloning, and gene-editing of embryos is also making waves in the international scientific community.Once the pigs are killed, their **corneas** - the thin, transparent films that cover the front of the eye - are removed from some of them and set aside, to be transplanted into humans. (眼角膜)

It is **by no means** an ordinary judicial case. Instead, it is a serious political incident. (绝不可能)

If you say that someone or something is a **liability**, you mean that they cause a lot of problems or embarrassment. (累赘) 

As the president's **prestige** (威望) continues to fall, they're beginning to consider him a liability  

**license plate**. (牌照)

The **brain drain** is no longer a big problem in China. (人才外流)

Make sure there is no **latency** when you are recording a song. (延迟)

**etiquette expert**. (礼仪专家)

**Ghosting** is breaking off a relationship (often an intimate relationship) by ceasing all communication and contact with the former partner without any apparent warning or justification, as well as ignoring the former partner's attempts to reach out or communicate. You got ghosted, or you are ghosting someone

You got **whupped**. (被彻底击败)

**Photolithography**  ASML (Advanced Semiconductor Materials International) is a Dutch company, and currently the largest supplier in the world of photolithography systems for the semiconductor industry. (光刻)

Most days of the year are unremarkable. They begin and they end, with no lasting memories in between. Most days have no impact on the course of life. May 23rd is a Wednesday…… If Tom had learned anything, it was that you can’t ascribe great cosmic significance to a simple earthly event. Coincidence. That’s all anything ever is. Nothing more than coincidence. Tom had finally learned there were no miracles. There is no such thing as fate. Nothing is meant to be. --- From the movie “500 days with Summer”.


He died of brain **hemorrhage**. (脑溢血)

**Temperament** (性情) the emotional part of someone’s character, especially how likely they are to be happy, angry, etc. Jill has such a lovely relaxed temperament.

**Temperamental** 1.likely to suddenly become upset, excited, or angry – used to show disapproval. Preston is particularly good at handling temperamental people. 2.relating to the emotional part of someone’s character. Temperamental differences between the couple is huge.

The election is just **ritual**. (仪式性的)

NPC is often considered a **rubber stamp** that passes motions according to the wishes of China's top leaders. (橡皮章)

The back tire was **punctured** by a piece of glass. (爆胎)

The mother is **nursing the baby**. (喂奶)

People can **dehydrate** in weather like this. (脱水)

Binocular **with a magnification of** ×12. (放大倍率)

If you describe someone as **snobbish**, you disapprove of them because they are too proud of their social status, intelligence, or taste. (势利眼)

You look beautiful only because you won a **genetic lottery** and you are the recipient of a legacy.

This doesn’t feel right and our **intervention** is a disaster. (干涉)

I am **empowering** you, go make a deal with our headquarters. (授权)

We can’t **indulge** kid anymore. (纵容，溺爱)

He was in a feverish delirium. (精神错乱)

He's religious but he doesn't try to **foist = impose** his beliefs on everyone. (强加于人)

**Maglev** is high-speed rail technology; the train is suspended on a magnetic cushion above a magnetized track and so travels free of friction.
Superconductivity maglev experiments are being performed by researchers at Xinan Jiaotong University. (超导磁悬浮)

Produce a **virtuous circle**. (良性循环)


<p style="color:Tomato;">The economic base determines the superstructure.</p>

During Stalin times, people could even inform against their parents. (告发)
In former times, the Czar was the king of Russia.

China urges the US to correct unfair anti-dumping duties on steel products. (反倾销)

Chinese people always **worship** foreign things but not it is changing and people are more proud of domestic products. (崇洋媚外)  

have blind faith in… (盲目崇拜)

Don’t **lose your dignity**. (失去尊严)

Young people buy luxurious bags only to **satisfy their vanity**. (满足虚荣心)

I am **skeptical** about your experimental results. (怀疑) Others here are more skeptical about the chances of justice being done.

The **proton and heavy-ion treatment** can more precisely deliver the radiation to the tumor and has fewer side effects when compared with traditional **radiotherapy**. (化疗)

Runoff from fertilizers in coastal areas causes **eutrophication** of the water column, leading to oceanic dead zones. (富营养化)

Since the global inception of the Haber-Bosch process in the early 20th century, **anthropogenic activity** has significantly influenced the marine nitrogen cycle. (人类活动) 

You made the whole building **short-circuit**. (短路)

He was on dialysis for seven years before his first transplant.
Excuse me, do you mean she needs **kidney dialysis**? (肾透析)

I suffered a **concussion** in an accident. (脑震荡)

He said he **was framed by** his ex-wife. (栽赃陷害)

The **reform and opening-up policy** in China changed the international status completely.

Is that something like a **provocation**? (挑衅)

Maybe he is just coming into his **prime** now. (鼎盛时期) This boy is doing things at 19 that I can only do in my prime

According to the **System of People’s Congress**, around 3000 delegates will be chosen to vote in the conference and making laws. (人民代表大会)

There will be a **runoff** between these two candidates on December 9th.(竞选)

In an interview with CNN, Marine Le Pen said France is "being attacked by **radical Islam** (伊斯兰激进分子)

If you say that someone is **servile**, you disapprove of them because they are too eager to obey someone above them or do things for them. (奴性的，恭顺的)
Australia is servile to US but will end up to be cannon fodder.
He was servile to the boss. 
The **Servility** of some people is harming the country. 

Further information will be declared and **stay tuned** (拭目以待)




